TARGET_NAMES += cell
TARGET_NAMES += genome
TARGET_NAMES += operations
TARGET_NAMES += peripheral
TARGET_NAMES += spec
TARGET_NAMES += world
TARGET_NAMES += web

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateForwarding
