TARGET_NAMES += cell
TARGET_NAMES += genome
TARGET_NAMES += operations
TARGET_NAMES += peripheral
TARGET_NAMES += services
TARGET_NAMES += spec
TARGET_NAMES += viz
TARGET_NAMES += web
TARGET_NAMES += world

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateForwarding
