TARGET_NAMES += CardinalIteratorAdapter
TARGET_NAMES += DummyGetter
TARGET_NAMES += IsAliveGetter
TARGET_NAMES += PhylogeneticRootGetter
TARGET_NAMES += ResourceStockpileGetter

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
