TARGET_NAMES += DummyFillColorMap
TARGET_NAMES += IsAliveColorMap
TARGET_NAMES += KinGroupIDFillColorMap
TARGET_NAMES += PhylogeneticRootColorMap
TARGET_NAMES += ResourceStockpileColorMap

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
