TARGET_NAMES += artists
TARGET_NAMES += border_colormaps
TARGET_NAMES += fill_colormaps
TARGET_NAMES += getters
TARGET_NAMES += renderers
TARGET_NAMES += util

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateForwarding
