TARGET_NAMES += ApoptosisRequest
TARGET_NAMES += ControllerMappedState
TARGET_NAMES += ResourceReceiveResistance
TARGET_NAMES += ResourceReserveRequest
TARGET_NAMES += ResourceSendLimit
TARGET_NAMES += ResourceSendRequest
TARGET_NAMES += SpawnArrest
TARGET_NAMES += SpawnRequest

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
