TARGET_NAMES += EventTags
TARGET_NAMES += GenerationCounter
TARGET_NAMES += Genome
TARGET_NAMES += MutationCounter
TARGET_NAMES += KinGroupID
TARGET_NAMES += RootID

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
