#pragma once
#ifndef DISH__GENOME_GENERATIONCOUNTER_HPP_INCLUDE
#define DISH__GENOME_GENERATIONCOUNTER_HPP_INCLUDE

namespace dish2 {



} // namespace dish2

#endif // #ifndef DISH__GENOME_GENERATIONCOUNTER_HPP_INCLUDE
