#pragma once
#ifndef DISH2_GENOME_GENERATIONCOUNTER_HPP_INCLUDE
#define DISH2_GENOME_GENERATIONCOUNTER_HPP_INCLUDE

namespace dish2 {



} // namespace dish2

#endif // #ifndef DISH2_GENOME_GENERATIONCOUNTER_HPP_INCLUDE
