TARGET_NAMES += Animator
TARGET_NAMES += GridViewer
TARGET_NAMES += ViewerCollection

TO_ROOT := $(shell git rev-parse --show-cdup)

test::
	npm install .

include $(TO_ROOT)/tests/MaketemplateWebRunning
