TARGET_NAMES += pare_keyname_filename
TARGET_NAMES += sha256_reduce
TARGET_NAMES += static_coarse_timer
TARGET_NAMES += try_with_timeout

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
