TARGET_NAMES += interpreted_introspective_state
TARGET_NAMES += introspective_state
TARGET_NAMES += raw_introspective_state

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateForwarding
