TARGET_NAMES += apoptosis_should_run
TARGET_NAMES += birth_setup_should_run
TARGET_NAMES += conduit_flush_should_run
TARGET_NAMES += cpu_execution_should_run
TARGET_NAMES += event_launching_should_run
TARGET_NAMES += inter_message_launching_should_run
TARGET_NAMES += intra_message_launching_should_run
TARGET_NAMES += resource_decay_should_run
TARGET_NAMES += resource_harvesting_should_run
TARGET_NAMES += resource_receiving_should_run
TARGET_NAMES += resource_sending_should_run
TARGET_NAMES += spawn_sending_should_run
TARGET_NAMES += state_input_jump_should_run

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
