TARGET_NAMES += AddToOwnState
TARGET_NAMES += MultiplyOwnState
TARGET_NAMES += OpLibrary
TARGET_NAMES += ReadNeighborState
TARGET_NAMES += ReadOwnState
TARGET_NAMES += SendInterMessage
TARGET_NAMES += WriteOwnState

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
