TARGET_NAMES += AddToOwnState
TARGET_NAMES += MultiplyOwnState
TARGET_NAMES += ReadNeighborState
TARGET_NAMES += ReadOwnState
TARGET_NAMES += SendInterMessageIf
TARGET_NAMES += WriteOwnStateIf

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
