TARGET_NAMES += GenomeMeshSpec
TARGET_NAMES += MessageMeshSpec
TARGET_NAMES += QuorumMeshSpec
TARGET_NAMES += ResourceMeshSpec
TARGET_NAMES += Spec
TARGET_NAMES += StateMeshSpec

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
