language: cpp

sudo: false

matrix:
  include:

    # clang-4
    - env: COMPILER=clang++-4.0
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-4.0
          packages:
            - clang++-4.0

    # clang-5
    - env: COMPILER=clang++-5.0
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
          packages:
            - clang++-5.0

    # clang-6
    - env: COMPILER=clang++-6.0
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang++-6.0

    # clang-7
    - env: COMPILER=clang++-7
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang++-7

    # clang-8
    - env: COMPILER=clang++-8
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang++-8

    # gcc-5
    - env: COMPILER=g++-5
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    # gcc-6
    - env: COMPILER=g++-6
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    # gcc-7
    - env: COMPILER=g++-7
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    # gcc-8
    - env: COMPILER=g++-8
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
          - g++-8
          sources:
          - ubuntu-toolchain-r-test

    # gcc-9
    - env: COMPILER=g++-9
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
          - g++-9
          sources:
          - ubuntu-toolchain-r-test

before_script:
  - export CXX=$COMPILER
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_CXX_FLAGS="-Werror" ..

script: make && ctest
