TARGET_NAMES += CardinalFillRenderer
TARGET_NAMES += CellBorderRenderer
TARGET_NAMES += CellFillRenderer

TO_ROOT := $(shell git rev-parse --show-cdup)

test::
	npm install .

include $(TO_ROOT)/tests/MaketemplateWebRunning
