TARGET_NAMES += ApoptosisRequestWrapper
TARGET_NAMES += CpuWrapper
TARGET_NAMES += IdentityWrapper
TARGET_NAMES += IsAliveWrapper
TARGET_NAMES += NeighborResourceReceiveResistanceWrapper
TARGET_NAMES += PeripheralWrapper
TARGET_NAMES += ResourceNodeOutputWrapper
TARGET_NAMES += ResourceReserveRequestWrapper
TARGET_NAMES += ResourceSendLimitWrapper
TARGET_NAMES += ResourceSendRequestWrapper
TARGET_NAMES += ResourceStockpileWrapper

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateRunning
